#!/usr/bin/env bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"
output="${Red}No instance supplied or instance not found. Run 'ax ls' to list all instances or 'ax rm --help' for more options.${Color_Off}"

###########################################################################################################
# Help Menu
#
function usage() {
    echo -e "${BWhite}Usage:${Color_Off} axiom-rm <pattern> [OPTIONS]"
    echo
    echo -e "${BWhite}Description:${Color_Off}"
    echo -e "  Delete one or more Axiom instances by name or pattern."
    echo -e "  Supports wildcards to match instance prefixes, suffixes, or substrings."
    echo
    echo -e "${BWhite}Arguments:${Color_Off}"
    echo -e "  <pattern>                Name or glob pattern to match instances (e.g. testy01, 'prefix*', '*sub*')"
    echo
    echo -e "${BWhite}Options:${Color_Off}"
    echo -e "  -f, --force              Skip confirmation prompts"
    echo -e "  -m, --multi              Enable multi-delete via API when supported"
    echo -e "  --debug                  Enable debug output (very verbose)"
    echo -e "  --help                   Show this help menu"
    echo
    echo -e "${BWhite}Examples:${Color_Off}"
    echo -e "  ${BGreen}axiom-rm testy01${Color_Off}                            # Delete a single instance by name"
    echo -e "  ${BGreen}axiom-rm 'testy*'${Color_Off}                           # Delete all instances starting with 'testy'"
    echo -e "  ${BGreen}axiom-rm '*tess*'${Color_Off}                           # Delete instances with 'tess' in their name"
    echo -e "  ${BGreen}axiom-rm '*' --force --multi${Color_Off}                # Delete all instances without prompts using multi-delete"
    echo
}

if [ -z "$1" ]; then
    usage
    exit
fi

force="false"
query=""
instance_names=""
multi=false

for var in "$@"; do
    case "$var" in
        -f|--force)
            force=true
            ;;
        -m|--multi)
            multi=true
            ;;
       --debug)
            set -xv
            ;;
        *)
            var=$(echo "$var" | sed 's/\\\*/\*/g') # Convert \* to *
            query="$query '$var'"
            ;;
    esac
done

instance_names=$(eval query_instances "$query")

if [[ "$instance_names" ]]; then
    if [ "$multi" == "true" ]; then
        delete_instances "$instance_names" "$force"
    else
        for instance in $instance_names; do
            echo -e "${Red}Deleting '$instance'...${Color_Off}"
            delete_instance "$instance" "$force"
        done
    fi
else
    >&2 echo -e "$output ${Color_Off}"
    exit
fi
