#!/usr/bin/env bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"
instance=""

# help menu
function help() {
    echo -e "${BWhite}Usage:${Color_Off} axiom-sync [INSTANCE ...] [OPTIONS]"
    echo
    echo -e "${BWhite}Description:${Color_Off}"
    echo -e "  Sync the home directory from one or more Axiom instances to your local machine."
    echo
    echo -e "${BWhite}Arguments:${Color_Off}"
    echo -e "  <instance>                One or more instance names to sync from"
    echo
    echo -e "${BWhite}Options:${Color_Off}"
    echo -e "  --help                    Show this help menu"
    echo
    echo -e "${BWhite}Examples:${Color_Off}"
    echo -e "  ${BGreen}axiom-sync instance01${Color_Off}                    # Sync from 'instance01'"
    echo -e "  ${BGreen}axiom-sync instance01 instance02${Color_Off}         # Sync from multiple instances"
    echo
}

# take one arugment and downloads the home dir of the instance supplied
function sync() {
generate_sshconfig
sync_path="$AXIOM_PATH/boxes/$1"
if [ ! -d "$sync_path" ]
 then
    mkdir -p "$AXIOM_PATH/sync/$1"
fi

echo -e "${BWhite}Syncing $instance to local file system... ${Color_Off}"
echo -n -e "${BGreen}"
rsync -avzr -e "ssh -F $AXIOM_PATH/.sshconfig" --progress --include-from="$AXIOM_PATH"/interact/includes/backup-files.txt "$instance":~/ "$AXIOM_PATH"/boxes/"$instance"/
echo -n -e "${Color_Off}"
echo -e "${BGreen}Instance '$instance' home directory successfully downloaded to $AXIOM_PATH/sync/$1 !${Color_Off}"
}

# if no arguments are specified print help menu
if [ "$1" == "" ]; then
 help
 exit
fi

# if arguments --help or -h are specified print help
if [[ "$@" == "--help" ]] || [[ "$@" == "-h" ]]; then
 help
 exit
fi

# iterate over the instance supplied and download the home dir recursively
if [[ ! -z "$1" ]]; then
mkdir -p $AXIOM_PATH/boxes
for var in "$@"
do
 instance=$var
 sync $1
done
fi
