#!/usr/bin/env bash

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"
output="${Red}No instance supplied or instance not found. Run 'ax ls' to list all instances or 'ax rm --help' for more options.${Color_Off}"

###########################################################################################################
# Help Menu
#
function usage() {
        echo -e "${BWhite}Description:${Color_Off}"
        echo -e "  Delete one or more cloud hosted compute devices"
        echo -e "  Supports globbing (wildcarding) to match instances based on patterns in their names, such as prefix, suffix, or substring matches."
        echo -e "${BWhite}Examples:${Color_Off}"
        echo -e "  ${Green}axiom-rm testy01${Color_Off} # Delete instance named 'testy01'"
        echo -e "  ${Green}axiom-rm 'testy*'${Color_Off} # Delete all instances starting with 'testy' (you may need to escape the asterisk)"
        echo -e "  ${Green}axiom-rm '*tess*'${Color_Off} # Delete all instances containing the string 'tess' (you may need to escape the asterisks)"
        echo -e "  ${Green}axiom-rm '\*' --force --multi${Color_Off} # Delete all instances on the account, avoid confirmation prompts, delete many instances with one API call"
        echo -e "${BWhite}Usage:${Color_Off}"
        echo -e "  <name> string (optional)"
        echo -e "    Name of the instance(s) to delete"
        echo -e "  -f/--force (optional)"
        echo -e "    Avoid confirmation prompts"
        echo -e "  -m/--multi (optional)"
        echo -e "    Delete multiple instances at once"
        echo -e "  --help (optional)"
        echo -e "    Display this help menu"
}

if [ -z "$1" ]; then
    usage
    exit
fi

force="false"
query=""
instance_names=""
multi=false

for var in "$@"; do
    case "$var" in
        -f|--force)
            force=true
            ;;
        -m|--multi)
            multi=true
            ;;
        *)
            var=$(echo "$var" | sed 's/\\\*/\*/g') # Convert \* to *
            query="$query '$var'"
            ;;
    esac
done

instance_names=$(eval query_instances "$query")

if [[ "$instance_names" ]]; then
    if [ "$multi" == "true" ]; then
        delete_instances "$instance_names" "$force"
    else
        for instance in $instance_names; do
            echo -e "${Red}Deleting '$instance'...${Color_Off}"
            delete_instance "$instance" "$force"
        done
    fi
else
    >&2 echo -e "$output ${Color_Off}"
    exit
fi
