#!/usr/bin/env bash

###################################################################
#  Header
#
AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"
source "$AXIOM_PATH/interact/includes/system-notification.sh"
begin=$(date +%s)
start="$(pwd)"
BASEOS="$(uname)"
account_path=$(ls -la $AXIOM_PATH/axiom.json | rev | cut -d " " -f 1 | rev)
accounts=$(ls -l "$AXIOM_PATH/accounts/" | grep "json" | grep -v 'total ' | awk '{ print $9 }' | sed 's/\.json//g')
current=$(ls -lh ~/.axiom/axiom.json | awk '{ print $11 }' | tr '/' '\n' | grep json | sed 's/\.json//g') > /dev/null 2>&1
provider="$(jq -r ".provider" "$AXIOM_PATH/axiom.json")"

###################################################################
#  Get default instance size if ax sizes default is used
#
get_default_size() {
  if [[ "$provider" == "azure" ]]; then
    default_size="Standard_B1ls"

  elif [[ "$provider" == "aws" ]]; then
    default_size="t2.medium"

  elif [[ "$provider" == "do" ]]; then
    default_size="s-1vcpu-1gb"

  elif [[ "$provider" == "ibm-classic" ]]; then
    default_size="C1_2X2X25"

  elif [[ "$provider" == "ibm-vpc" ]]; then
    default_size="cx2-2x4"

  elif [[ "$provider" == "linode" ]]; then
    default_size="g6-standard-1"

  elif [[ "$provider" == "gcp" ]]; then
    default_size="n1-standard-1"

  elif [[ "$provider" == "hetzner" ]]; then
    default_size="cx22"

  elif [[ "$provider" == "scaleway" ]]; then
    default_size="DEV1-S"

  elif [[ "$provider" == "exoscale" ]]; then
    default_size="standard.medium"

  else
    echo "Error: Unknown provider '$provider'"
    exit 1
  fi
}

###########################################################################################################
# Help Menu:
#
function usage() {
    echo -e "${BWhite}Usage:${Color_Off} axiom-sizes [COMMAND] [OPTIONS]"
    echo
    echo -e "${BWhite}Description:${Color_Off}"
    echo -e "  Manage the default instance size used by axiom-init and axiom-fleet."
    echo -e "  You can list, select, restore, or print the currently selected size."
    echo
    echo -e "${BWhite}Commands:${Color_Off}"
    echo -e "  ls                         List all available instance sizes"
    echo -e "  get                        Print the current default instance size from axiom.json"
    echo -e "  select <size>              Set a new default size (must be a valid option from 'ls')"
    echo -e "  default                    Restore the original default size"
    echo
    echo -e "${BWhite}Options:${Color_Off}"
    echo -e "  --debug                    Enable debug output (very verbose)"
    echo -e "  --help                     Show this help menu"
    echo
    echo -e "${BWhite}Examples:${Color_Off}"
    echo -e "  ${BGreen}axiom-sizes ls${Color_Off}                              # List sizes available from provider"
    echo -e "  ${BGreen}axiom-sizes get${Color_Off}                             # Show the currently selected size"
    echo -e "  ${BGreen}axiom-sizes select s-4vcpu-8gb${Color_Off}              # Set 's-4vcpu-8gb' as the default"
    echo -e "  ${BGreen}axiom-sizes default${Color_Off}                         # Reset to original default size"
    echo
}

###########################################################################################################
#  Declare defaut variables
#
list="false"
help="true"
use="false"
default_size="false"

###########################################################################################################
#  Parse command line arguments
#
if [[ "$@" == "--help" ]] || [[ "$@" == "-h" ]] || [[ "$@" == "" ]]; then
usage
exit
fi
i=0
for arg in "$@"
do
    i=$((i+1))
    if [[  ! " ${pass[@]} " =~ " ${i} " ]]; then
        set=false
       if [[ "$arg" == "--debug" ]]; then
            set -xv
            set=true
            pass+=($i)
        fi
        if [[ "$arg" == "default" ]]; then
            restore_default_size=true
            set=true
            pass+=($i)
        fi
        if [[ "$arg" == "select" ]] ||[[ "$arg" == "set" ]] || [[ "$arg" == "use" ]] ; then
            n=$((i+1))
            use=true
            new_size=$(echo ${!n})
            set=true
            pass+=($i)
            pass+=($n)
        fi
        if [[ "$arg" == "ls" ]] || [[ "$arg" == "list" ]]; then
            list="true"
            set=true
            pass+=($i)
        fi
        if [[ "$arg" == "--help" ]] || [[ "$arg" == "-h" ]] || [[ "$arg" == "help" ]]; then
            usage
            exit
            set=true
            pass+=($i)
        fi
        if [[ "$arg" == "get" ]] ; then
            get="true"
            set=true
            pass+=($i)
        fi
        if  [[ "$set" != "true" ]]; then
            args="$args $arg"
        fi

    fi
done

# Get the default size in /.axiom/accout/account.json
#
if [[ "$get" == "true" ]]; then
 echo -e "${Green}Displaying Account Info from: $current${Color_Off}"
 cat $(echo $account_path)
 exit 1

# List sizes
#
elif [[ "$list" == "true" ]]; then
 echo -e "${Green}Listing Available Instance Sizes for Cloud provider in Account: $current${Color_Off}"
 sizes_list
 exit 1

# Use new instance size by name. Run axiom-init or axiom-fleet to use after updating
#
elif [[ "$use" == "true" ]]; then
 # Check if size is unset or emtpy
 if [ -z "${new_size+x}" ] || [ -z "$new_size" ]; then
  echo -e "${Red}No size provided, unable to select size.. exiting${Color_Off}"
  exit
 fi

 old="$(cat "$AXIOM_PATH/axiom.json" | jq -r '.default_size')"
 sizes_list | grep -q -w $new_size || { echo -e "${Red}Failed to find instance size with name: "$new_size"... exiting${Color_Off}" ; \
 echo -e "${Red}To print all available intance sizes, run ax sizes ls${Color_Off}" ; exit 1; }
 jq '.default_size="'$new_size'"' <"$account_path">"$AXIOM_PATH"/tmp.json ; mv "$AXIOM_PATH"/tmp.json "$account_path"
 echo -e "${Green}Successfully updated default_size $old with new instance size $new_size in account: $current${Color_Off}"
 echo -e "${Green}Run axiom-init or axiom-fleet to use it!${Color_Off}"

# Restore default size if ax sizes default is used
##
elif [[ "$restore_default_size" == "true" ]]; then
 get_default_size
 if [[ "$provider" == "ibm-classic" ]]; then
  ram="$(echo $default_size | cut -d , -f 1)"
  cpu="$(echo $default_size | cut -d , -f 2)"
  jq '.default_size="'$ram'"' <"$account_path">"$AXIOM_PATH"/tmp.json ; mv "$AXIOM_PATH"/tmp.json "$account_path"
  jq '.cpu="'$cpu'"' <"$account_path">"$AXIOM_PATH"/tmp.json ; mv "$AXIOM_PATH"/tmp.json "$account_path"
  echo -e "${Green}Successfully restored default size, updated ~/.axiom/axiom.json to use ram: $ram and cpu: $cpu in account: $current${Color_Off}"
  echo -e "${Green}Run axiom-init or axiom-fleet to use it!${Color_Off}"
 else
  jq '.default_size="'$default_size'"' <"$account_path">"$AXIOM_PATH"/tmp.json ; mv "$AXIOM_PATH"/tmp.json "$account_path"
  echo -e "${Green}Successfully restored default size, updated ~/.axiom/axiom.json with default instance size $default_size in account: $current${Color_Off}"
  echo -e "${Green}Run axiom-init or axiom-fleet to use it!${Color_Off}"
fi

# Valid command not provided
##
else
usage
fi
