#!/bin/bash

profile="$1"
query="$2"
type="install"
cache=""

AXIOM_PATH="$HOME/.axiom"
source "$AXIOM_PATH/interact/includes/vars.sh"
source "$AXIOM_PATH/interact/includes/functions.sh"

function help() {
  echo -e "${BWhite}Usage:${Color_Off}"
  echo -e "  axiom-deploy [OPTIONS] <profile> <instance>"
  echo -e ""
  echo -e "  <profile>    Name of the deployment profile to apply (profiles in ~/.axiom/profiles)"
  echo -e "  <instance>   Name of the target instance to deploy to"
  echo -e ""
  echo -e "${BWhite}Options:${Color_Off}"
  echo -e "  --cache      Use SSH cache (if instance was recently accessed)"
  echo -e "  --remove     Uninstall the profile from the instance"
  echo -e "  --list       List all available profiles"
  echo -e "  --help       Display this help menu"
  echo -e ""
  echo -e "${BWhite}Example:${Color_Off}"
  echo -e "  ${BGreen}axiom-deploy openvpn jerry01${Color_Off}  # Deploy 'openvpn' profile to instance 'jerry01'"
  echo -e ""
}

for var in "$@"
do
    if [[ "$var" == "--remove" ]]; then
        type="uninstall"
    fi

    if [[ "$var" == "--cache" ]]; then
        cache="true"
    fi

    if [[ "$var" == "--help" ]] || [[ "$var" == "-h" ]]; then
        help
        exit 0
    fi

    if [[ "$var" == "--list" ]]; then
        echo -e "${BWhite}Deployment profiles${Color_Off}"
        (echo '"ID","Description"'; cat "$AXIOM_PATH/profiles/"* | jq -r '[.name,.description] | @csv')  | column -t -s, | tr -d '"' | perl -pe '$_ = "\033[0;37m$_\033[0;34m" if($. % 2)'
        exit 0
        fi
    done

    if [[ -z "$1" ]]; then
	help
        echo -e "${Red}Error: first argument must be a deployment profile, list all profiles with ${Green}ax deploy --list${Color_Off}"
	exit
    fi

    if [[ -z "$2" ]]; then
        echo -e "${Red}Error: second argument must be an instance name, list all instances with ${Green}ax ls${Color_Off}"
        exit 0
    fi

    if [[ "$profile" == "" ]]; then
        help
    else
        name="${type}ing"
        prof_path="$AXIOM_PATH/profiles/$profile.json"

        if [[ -f "$prof_path" ]]; then
            echo -e "${BWhite}$name '$profile' : '$query'"

            [[ "$cache" == "" ]] && generate_sshconfig

            count=$(query_instances_cache "$query" | wc -c)
            id="$RANDOM"
            script="$AXIOM_PATH/tmp/$id.sh"

            jq -r ".$type[]" "$prof_path" > "$script"
            chmod +x "$script"

        if [[ "$count" -gt 1 ]]; then
            echo -e "${BWhite}Uploading profile to '$query'${Color_Off}${BGreen}"
            axiom-scp "$script" "$query":"/tmp/$id.sh" --cache
            axiom-exec "/tmp/$id.sh" -i "$query" --cache
            echo -e "${BGreen}Installation Successful!${Color_Off}"
            echo -e "${BWhite}Notes${Color_Off}${BGreen}"
            jq -r ".notes" "$prof_path"
            echo -e -n "${Color_Off}"
        else
            echo -e "${BRed}Error no instances found...${Color_Off}"
        fi
    else
        echo -e "${BRed}Error: Profile '$profile' does not exist.${Color_Off}"
    fi
fi
