#!/bin/bash

ip=$(dig +short myip.opendns.com @resolver1.opendns.com)
echo ""
cat << EOF
 █████╗ ██╗  ██╗
██╔══██╗╚██╗██╔╝
███████║ ╚███╔╝ 
██╔══██║ ██╔██╗ 
██║  ██║██╔╝ ██╗
╚═╝  ╚═╝╚═╝  ╚═╝

EOF
echo ""
echo -e "Public IP: \033[0;34m$ip\033[0m - Instance: \033[0;34m$(hostname)\033[0m"
echo ""
