
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$HOME/.rvm/bin:/root/osmedeus-base/binaries:$PATH"
export GOPATH=/home/op/go
export PS1='\[\033[01;32m\]$(whoami)@$(hostname) \[\033[0m\]'
alias ls="ls --color=auto"
